import { AiFillStar } from "react-icons/ai";

const data = [
    {
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZWXq6JfgsUYEICv-egh6o-dNUXlOTKBWAgg&usqp=CAU",
        title:"Minty Halter Neck Dress", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"123",
        prevPrice:"$100",
        newPrice:"$80",
        company:"Deewa",
        color:"green",
        category:"Fashion Wear",
        },
        {
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMOruao44R5BjWopN-lNTHrNw13SD_FD_TTQ&usqp=CAU",
        title:"Loft Dresses", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"101",
        prevPrice:"$90",
        newPrice:"$50",
        company:"Charu",
        color:"green",
        category:"Fashion Wear",
        },
        {
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ7qF-Qh_qJfePD6Zzt6_kUASKjh8xApZsG1Rmi4DzOYsYwQWMglUB9y7JVIbZ59wPEuo&usqp=CAU",
        title:"Long White Buttoning", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"80",
        prevPrice:"$150",
        newPrice:"$120",
        company:"TEREZA",
        color:"white",
        category:"Fashion Wear",
        },
        {
        img:"https://i5.walmartimages.com/asr/b8b0e4c8-d50f-423c-a47e-9a6ec0699f13.7deb2bc6d843f939d6429c5d81cefd82.jpeg",
        title:"casual Dress V Neck", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"51",
        prevPrice:"$100",
        newPrice:"$80",
        company:"TEREZA",
        color:"green",
        category:"Fashion Wear",
        },
        {
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7G7NYNex1iTiHjME8aslsnn86psvYnTfnDJMLTv2Pd-wHuQ3-DXhdT34Vv4PLue1k-eA&usqp=CAU",
        title:"white Fashion", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"32",
        prevPrice:"$130",
        newPrice:"$100",
        company:"FabClub",
        color:"white",
        category:"Fashion Wear",
        },
        {
        img:"https://images.meesho.com/images/products/97530189/emymz_512.jpg",
        title:"Women Westrn Dress", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"16",
        prevPrice:"$100",
        newPrice:"$90",
        company:"Kiya",
        color:"white",
        category:"Fashion Wear",
        },
        {
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb8vVJkfrmrP3pp_YVIrDbZxC8jQhTFFd7XMwoKAWmjhQqV7UBSFklwFt0gzQk1viF94A&usqp=CAU",
        title:"Pretty Little Thing Fashion", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"75",
        prevPrice:"$90",
        newPrice:"$80",
        company:"AHIKA",
        color:"white",
        category:"Fashion Wear",
        },
        {
        img:"https://rukminim2.flixcart.com/image/500/500/kura1e80/dress/f/o/r/xl-1151-sheetal-associates-original-imag7ta56srcgcyy.jpeg?q=90&crop=false",
        title:"Black Fashion", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"64",
        prevPrice:"$100",
        newPrice:"$90",
        company:"Ishin",
        color:"black",
        category:"Fashion Wear",
        },
        {
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhc0sXle30iGXuiE5q5Mfdw8wAU05Luu17Fk1dFU8-Mi2X8LzraKOTfQ9DSkN8jS5zIHI&usqp=CAU",
        title:"SOIE women", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"67",
        prevPrice:"$110",
        newPrice:"$100",
        company:"TEREZA",
        color:"black",
        category:"Fashion Wear",
        },
        {
        img:"https://images.meesho.com/images/products/91995950/kei8d_512.jpg",
        title:"Western Fit & Flare Piece", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"542",
        prevPrice:"$120",
        newPrice:"$100",
        company:"Ishin",
        color:"black",
        category:"Fashion Wear",
        },
        {
        img:"https://n.nordstrommedia.com/id/sr3/c72f86c0-5fd3-4cd9-b174-442b6b90e62f.jpeg?h=500&w=500&dpr=2",
        title:"Nordstrom Rack", 
        star:<AiFillStar className="rating-star"/>,
        reviews:"2121",
        prevPrice:"$120",
        newPrice:"$90",
        company:"Ishin",
        color:"yellow",
        category:"Fashion Wear",
        },
        
    {
    img:"https://5.imimg.com/data5/ANDROID/Default/2021/1/VC/SF/FL/29603120/product-jpeg-500x500.jpg",
    title:"Indian Women Dress", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"24",
    prevPrice:"$100",
    newPrice:"$80",
    company:"Charu",
    color:"blue",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjWjoytEm5wLxLnPqlP6VnaCOuRCcIXsb9mknX0EiM8LsyKpPe3ZuaeP7aLjGd2loe_s0&usqp=CAU",
    title:"Indian Women Salwar", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"56",
    prevPrice:"$140",
    newPrice:"$100",
    company:"Charu",
    color:"black",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SPjTEK0LXgMcHKiTT6tO51B0z2UkDHInkH7OUWynP_SrFE0juOgJ_Kq8JNymYqXRxxQ&usqp=CAU",
    title:"Treditional Designer Dress", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"31",
    prevPrice:"$100",
    newPrice:"$90",
    company:"KALINI",
    color:"brown",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://static-01.daraz.pk/p/2af6b51c8f2fc54513fcbccb5769bf17.jpg_500x500.jpg_.webp",
    title:"Ladies Dress Chiffon Crincle", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"6",
    prevPrice:"$150",
    newPrice:"$120",
    company:"Vishudh",
    color:"brown",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGxEnj-opy9qKo5NwHpdGilI5nL0mzGG4g0g&usqp=CAU",
    title:"Blue Designer Dress", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"103",
    prevPrice:"$120",
    newPrice:"$100",
    company:"AHIKA",
    color:"blue",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4vRQ1vL1yVLx_SvMmaCa7jaYh7PRE0JAUwAGYNwwUALXnAVIi5JgvbbhOsDOHQzUQlLk&usqp=CAU",
    title:"Army Babydoll Dress", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"44",
    prevPrice:"$130",
    newPrice:"$80",
    company:"AHIKA",
    color:"black",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSmbbuvstehlQylMaYdw7Ob8Yx_roaUYnb8Q&usqp=CAU",
    title:"Indian Ethnic Wear", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"10",
    prevPrice:"$140",
    newPrice:"$110",
    company:"Deewa",
    color:"pink",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRihvrpNCONe1Cnsmz92auv6EjEZLXSiGmGOUptzbx2MkoS4Q5XhtgBQsSHPqGhbPEzhAw&usqp=CAU",
    title:"Rosy Pink Ethnic Wear", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"22",
    prevPrice:"$150",
    newPrice:"$120",
    company:"FabClub",
    color:"pink",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://khwaissh.com/wp-content/uploads/2022/08/WhatsApp-Image-2022-08-26-at-10.44.57-AM.jpeg",
    title:"New Designer Party Wear", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"68",
    prevPrice:"$150",
    newPrice:"$120",
    company:"FabClub",
    color:"orange",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgSYHI6XL2RMo1gnOo-KIEaQPNU0flWAbncpdHeaesDPt0CCpGHCs2xfVJbhMiElKOC1g&usqp=CAU",
    title:"Party Wear Fancy Dress", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"45",
    prevPrice:"$100",
    newPrice:"$80",
    company:"Deewa",
    color:"orange",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSX2xw0Gv8WOTnCBU7DPHXeZjE7ROCUdFTMMJEjct0U_J-o5pl4iuC8rkIBNrl9RF4ryc4&usqp=CAU",
    title:"Indian Dress", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"88",
    prevPrice:"$80",
    newPrice:"$50",
    company:"Kiya",
    color:"green",
    category:"Salwar and Dupatta",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnVhsYzXXUYgl0e_3gzPmPqteag1TumsBFPKO5IW1Ek6sa0n3DjPyJ6dGt79_X2exJIcI&usqp=CAU",
    title:"Traditional Indian Clothing", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"76",
    prevPrice:"$100",
    newPrice:"$70",
    company:"KALINI",
    color:"green",
    category:"Salwar and Dupatta",
    },
    
    
    
    
    {
    img:"https://5.imimg.com/data5/LE/VT/JJ/SELLER-49024477/women-clothes.jpg",
    title:"Anarkali Wedding Dress", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"432",
    prevPrice:"$220",
    newPrice:"$200",
    company:"Sangria",
    color:"brown",
    category:"Lehenga Choli",
    },
    {
    img:"https://www.brides.com/thmb/dp7lL8mKHsvGHhphZfGMJo3SIy8=/735x0/MJ112720tandon-Friday-1092-6ad8260df26d4f1c94728f86484f49f4.jpg",
    title:"Rose Red Wedding Dress", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"156",
    prevPrice:"$250",
    newPrice:"$210",
    company:"Sangria",
    color:"red",
    category:"Lehenga Choli",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3jq8WFw-cXRMcEA2va6-7C3qwG2_ZtuL-0jQWkKVkwylrSi55eAwFEnQc0xf-rANW934&usqp=CAU",
    title:"Wedding Dress for dulhan", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"66",
    prevPrice:"$250",
    newPrice:"$190",
    company:"Charu",
    color:"red",
    category:"Lehenga Choli",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNBVN8U7pKmpO0u9mizVd5foUKNwJHW1D4UDc8LgwBhPQ-xn_HsbB96HEmtpn8BQ-XY1E&usqp=CAU",
    title:"Designer Wear", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"89",
    prevPrice:"$210",
    newPrice:"$200",
    company:"KALINI",
    color:"orange",
    category:"Lehenga Choli",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj4xqYCU9x_3Pu7QyiofP6-wihjct29j-_0A&usqp=CAU",
    title:"Royal Blue lehenga", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"100",
    prevPrice:"$220",
    newPrice:"$210",
    company:"KALINI",
    color:"blue",
    category:"Lehenga Choli",
    },
    
    
    
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbcSIN5j3UAodGmpnG-9EuJNjMpUbfq3OnsA&usqp=CAU",
    title:"Women T-Shirts", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"39",
    prevPrice:"$90",
    newPrice:"$50",
    company:"TEREZA",
    color:"black",
    category:"T-Shirts and Tops",
    },
    
    {
    img:"https://rukminim2.flixcart.com/image/500/500/xif0q/top/u/k/4/m-coller-tops-style-prezone-original-imagjuvvhzxhmf4y.jpeg?q=90&crop=false",
    title:"Tops - Best Prices", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"97",
    prevPrice:"$110",
    newPrice:"$100",
    company:"FabClub",
    color:"brown",
    category:"T-Shirts and Tops",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSO7Fl2JGNQuiJigIB8iwIQEBrGq9j7j-O7Xvt4IWalH8EenBz7V46HYLovaU75PWnM9yI&usqp=CAU",
    title:"T Shirts for Women", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"333",
    prevPrice:"$80",
    newPrice:"$60",
    company:"FabClub",
    color:"yellow",
    category:"T-Shirts and Tops",
    },
    {
    img:"https://assets.myntassets.com/dpr_1.5,q_60,w_500,c_limit,fl_progressive/assets/images/17811478/2022/4/8/3e7d49b5-2dab-4bbd-a75b-274784c91c761649401342737SeraPinkTieandDyeChiffonTop1.jpg",
    title:"Women Tops", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"238",
    prevPrice:"$120",
    newPrice:"$110",
    company:"Deewa",
    color:"pink",
    category:"T-Shirts and Tops",
    },
    {
    img:"https://assets.myntassets.com/dpr_1.5,q_60,w_500,c_limit,fl_progressive/assets/images/17784334/2022/4/6/e90130a9-a667-48c4-baf0-0a702067398a1649256286179SeraBlackFloralPrintGeorgetteWrapTop1.jpg",
    title:"Women Tops", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"95",
    prevPrice:"$120",
    newPrice:"$100",
    company:"Deewa",
    color:"black",
    category:"T-Shirts and Tops",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISVVBoSt7vKi1fKolAhQXAJaVLrI8lDD8PkRdCG1dgWHBJsSbe6j0soGn6ST8UYoNjQs&usqp=CAU",
    title:"Blue Solid Color Top", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"423",
    prevPrice:"$110",
    newPrice:"$90",
    company:"Charu",
    color:"blue",
    category:"T-Shirts and Tops",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStJ99FN7_gozDn_sodu0JpTpOfZJ-3NJ2N-R3scrFQEXOrxGDDdrR8w8rMlfbDgx0hzMg&usqp=CAU",
    title:"Green shaded georgette Top", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"314",
    prevPrice:"$100",
    newPrice:"$90",
    company:"Charu",
    color:"green",
    category:"T-Shirts and Tops",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnk8mpphLxyPNmpOKcq1f0gnSf1PUxhMG44w&usqp=CAU",
    title:"tshirt Women", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"197",
    prevPrice:"$90",
    newPrice:"$70",
    company:"TEREZA",
    color:"white",
    category:"T-Shirts and Tops",
    },
    
    
    
    
    {
    img:"https://assets.ajio.com/medias/sys_master/root/20201230/EmiM/5fec4438f997dd8c17b424cc/-473Wx593H-461786736-blue-MODEL.jpg",
    title:"Washed Full-Length Slim Jeans", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"235",
    prevPrice:"$170",
    newPrice:"$150",
    company:"Sangria",
    color:"blue",
    category:"Jeans",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgaMia1bIY43bjOALzA9jBfoEPqlJlblld5n0P8M64K_fcOI9LDt5p9T3htIjvg_BY6sw&usqp=CAU",
    title:"Ankle-Length Slim Fit Jeans", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"432",
    prevPrice:"$180",
    newPrice:"$160",
    company:"Kiya",
    color:"blue",
    category:"Jeans",
    },
    {
    img:"https://imagescdn.aeo.in/img/app/brands/ae/jeans/women/Skinny_11-12-2019.jpg?auto=format",
    title:"Women Denim Jeans", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"65",
    prevPrice:"$200",
    newPrice:"$180",
    company:"Kiya",
    color:"blue",
    category:"Jeans",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3gNBnBzGNEPvZJHSdtfxaar71mC7LrEmRPWJcHX0Mk2ViIsuRibSMoZDFhXyPYsHbvMs&usqp=CAU",
    title:"Mid Rise Sanded Ripped Jeans", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"85",
    prevPrice:"$200",
    newPrice:"$190",
    company:"Sangria",
    color:"blue",
    category:"Jeans",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn46npHlClwO7C0C-5SaL61o28mjEbEBEfXgytUsfjezz2nJEFsM-ZOyddHU9rBETfz8Y&usqp=CAU",
    title:"Super high waist skinny Jeans", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"92",
    prevPrice:"$220",
    newPrice:"$200",
    company:"TEREZA",
    color:"black",
    category:"Jeans",
    },
    {
    img:"https://assets.ajio.com/medias/sys_master/root/20230602/12ut/64793edf42f9e729d70ddf25/-473Wx593H-461431038-black-MODEL.jpg",
    title:"High Rise Flared Jeans", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"437",
    prevPrice:"$220",
    newPrice:"$200",
    company:"TEREZA",
    color:"black",
    category:"Jeans",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfrSIiNVY8uc2PZRWRlGb3K8RT_F6AvLvTukV3ub38SfnPbIE2hs1m5eqldgtQKrOaSW8&usqp=CAU",
    title:" Women White Jeans", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"12",
    prevPrice:"$200",
    newPrice:"$190",
    company:"FabClub",
    color:"white",
    category:"Jeans",
    },
    
    
    
    
    
    
    
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqfywKZLwUjWhFMmyKAxd20onsnBqOOJkGn7W0p_-yq1zQJWPotC25P4dppb45DAw2eec&usqp=CAU",
    title:"Denim Jacket For Girls", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"55",
    prevPrice:"$170",
    newPrice:"$150",
    company:"AHIKA",
    color:"blue",
    category:"Jackets",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI0Jy7pDu9X0diLCRGbDyb-dvu6MBmOvVcotldMmG0HKOZf1wfIcqWOTc2R7ueX8o77x0&usqp=CAU",
    title:"Trendy Denim Jacket for Women's", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"74",
    prevPrice:"$180",
    newPrice:"$130",
    company:"AHIKA",
    color:"blue",
    category:"Jackets",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM1UZDRTzyfP6gg9HW3O5gpup9edABkFZK_AEFcTUmeW_BuirLjArSEZV8eDKgJ5RR5QI&usqp=CAU",
    title:"JACKET", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"253",
    prevPrice:"$190",
    newPrice:"$150",
    company:"Sangria",
    color:"green",
    category:"Jackets",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_mx56sYVG9Kx7jRyaSXUc8qaS-auQllr84g&usqp=CAU",
    title:"Women regulat fit Solid Coat", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"215",
    prevPrice:"$250",
    newPrice:"$200",
    company:"FabClub",
    color:"brown",
    category:"Jackets",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStEWx9eJR7xwHgXUqIFP_9coYQySmG1Z2-sgUm7T0tflp-6BCnYDddUbomwdssPapB5_Y&usqp=CAU",
    title:"Khaki Solid Casual Jacket", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"64",
    prevPrice:"$250",
    newPrice:"$180",
    company:"FabClub",
    color:"yellow",
    category:"Jackets",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWlfspSKEs2aOwlDR0soy1tR-BJEnEenXJlA&usqp=CAU",
    title:"Jacket For Women", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"99",
    prevPrice:"$170",
    newPrice:"$140",
    company:"TEREZA",
    color:"black",
    category:"Jackets",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOfxBlVjODiBnTE4wYXFnAxB4TaejcB6W6EQ&usqp=CAU",
    title:"Women JAcket Coat Long Sleeve", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"132",
    prevPrice:"$180",
    newPrice:"$150",
    company:"TEREZA",
    color:"white",
    category:"Jackets",
    },
    
    
    
    
    
    
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRS1O__x0UDN2ULiBrQwkF6oQlbtOomVKKc_ktEBEct6LvQdC0dLlOcxV59LbWF8_ad_vA&usqp=CAU",
    title:"Madumani Silky Cotton...", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"356",
    prevPrice:"$200",
    newPrice:"$130",
    company:"Charu",
    color:"green",
    category:"Sarees",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThIgjYw62VygL9ytcN92LMn_8kXrrlxi7lYKooPo8Gtrf1shWDcjLOykEOzAr0LJmR1y4&usqp=CAU",
    title:"Royal Blue Lichi Saree", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"86",
    prevPrice:"$220",
    newPrice:"$180",
    company:"Charu",
    color:"blue",
    category:"Sarees",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP_wa7miCBCbDpmCJzT3Jy3UFvBoFOJMvw3Q&usqp=CAU",
    title:"Saree for Women", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"24",
    prevPrice:"$190",
    newPrice:"$170",
    company:"Deewa",
    color:"red",
    category:"Sarees",
    },
    {
    img:"https://i.etsystatic.com/32863075/r/il/4c9ff6/4156403850/il_570xN.4156403850_98si.jpg",
    title:"White Flower Red Saree", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"37",
    prevPrice:"$190",
    newPrice:"$170",
    company:"KALINI",
    color:"white",
    category:"Sarees",
    },
    {
    img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVwaaUne-VvCajaETab3HSI1Cxkj0jp08pSWAFkNwrLtnaN7XFi8WxwkQCRD9J5NZ6MeA&usqp=CAU",
    title:"White Netted Red Saree", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"96",
    prevPrice:"$210",
    newPrice:"$190",
    company:"KALINI",
    color:"white",
    category:"Sarees",
    },
    {
    img:"https://www.ethnicplus.in/media/catalog/product/cache/1d5df636cf8c8988ea2d2c570bb7c21d/f/b/fb_l65_1_.jpeg",
    title:"Party Wear Pink Saree", 
    star:<AiFillStar className="rating-star"/>,
    reviews:"108",
    prevPrice:"$250",
    newPrice:"$200",
    company:"Sangria",
    color:"pink",
    category:"Sarees",
    },
    
    ];

    export default data;